### ISSUE TITLE
push一个controller,pop回来会导致tagCollectionView界面发生偏移

### ISSUE THREAD

**Issue by Rakutou** [changjianfeishui/XBScrollPageController#1]
如果在XBTagTitleCell去掉_titleLabel.translatesAutoresizingMaskIntoConstraints = NO就不会这样了.
麻烦看一下.
最后还是学习了.

**Comment by changjianfeishui** [comment]
谢谢反馈,pageCell是去了的,这个可能没注意到

**Comment by changjianfeishui** [comment]
已修正,谢谢反馈

**Comment by sn5diphone6** [comment]
你好  在tabBar的控制下，如果DemoViewController是第一项，selectionIndicator位置能够正确显示。如果是非第一项，selectionIndicator一开始的位置会有偏差，需滑动一下才能正确显示。 另外真的很棒，学到了很多。谢谢。

**Comment by changjianfeishui** [comment]
你好,已更新一个手动设置选中的方法,Xcode7,iOS9测试未发现有偏差问题,具体参见已更新的Demo

**Comment by sn5diphone6** [comment]
我也是在Xcode7,iOS9测试遇到了这个问题。会不会是我加TabBar出了问题。 用了手动设置选中的方法后，当index大于等于1的时候  selectionIndicator位置能够正确显示， 等于0的话  还是出现了偏差。

**Comment by changjianfeishui** [comment]
方便的话截个图,3Q~
